output_folder: "../logs"
loader:
  batch_size: 32
dataset:
  name: "COCO"
  train: "train"
  test: "val"
  img_folder: "../data/coco_dataset"
  json_folder: "../data/coco_dataset/annotations"
input:
  img_min_size: [288, 320, 352, 384, 416, 448, 480]
  img_max_size: 640
model:
  fpn_feats_dim: 128
  backbone_freeze_bn: False
opt:
  warmup_epochs: 3
  epochs: 12
  learning_rate: 0.02

# other parameters can be specified in this yaml file
# e.g. the following lines will reset the number of training epochs to 8
#opt:
#  epochs: 8

# see config.py for more details
